# [[main]]
#   name = "Log"
#   pageRef = "posts"
#   weight = 10

[[main]]
  name = "Itinerary"
  pageRef = "itinerary"
  weight = 20

[[main]]
  name = "Process"
  pageRef = "process"
  weight = 30

[[main]]
  name = "About the trip"
  pageRef = "about_trip"
  weight = 40

[[main]]
  name = "About me"
  pageRef = "about_me"
  weight = 50

[[footer]]
  name = "White Ribbon"
  url = "https://www.vitagronabandet.se/en/white-green-ribbon/"
  weight = 10
